apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  selector:
    app: app-one
  ports:
    - name: app-one
      protocol: TCP
      port: 80                                                                    
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  selector:
    app: app-two
  ports:
    - name: app-two
      protocol: TCP
      port: 80                                                                    
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  selector:
    app: app-three
  ports:
    - name: app-three
      protocol: TCP
      port: 80                                                                    
      targetPort: 8080