apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
    - name: app1
      protocol: TCP
      port: 80                                                                    
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
  ports:
    - name: app2
      protocol: TCP
      port: 80                                                                    
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  selector:
    app: app3
  ports:
    - name: app3
      protocol: TCP
      port: 80                                                                    
      targetPort: 8080