Vagrant.configure("2") do |config|
  config.vm.define "rsafSx" do |control|
    control.vm.provider "virtualbox" do |v|
      # v.gui = true
      v.memory = 1000
      v.cpus = 1
      v.name = "rsafSx"
    end
    # config.vm.network "public_network"
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    control.vm.box = "generic/alpine318"
    control.vm.network "private_network", ip: "192.168.56.110"
  end

  config.vm.define "rsafSW" do |control|
    control.vm.provider "virtualbox" do |v|
      v.name = "rsafSW"
      v.memory = 500
      v.cpus = 2
    end
    # config.vm.network "public_network"
    # config.vm.network "forwarded_port", guest: 80, host: 8081
    control.vm.box = "generic/alpine318"
    control.vm.network "private_network", ip: "192.168.56.111"
  end
end

