# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX="ubuntu/jammy64"
# BOX_VERSION="2011.0"
BOX_URL="https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64-vagrant.box"

VM_MASTER_NAME="rsafS"
VM_WORKER_NAME="rsafSW"
MASTER_IP="192.168.56.110"
WORKER_IP="192.168.56.111"

CPU=1
MEM=1024

HOST_SRC_PATH=
VM_SRC_PATH=

Vagrant.configure("2") do |config|

  config.vm.box = BOX
  config.vm.box_url= BOX_URL
  


  # this is Master Node.
  config.vm.define VM_MASTER_NAME do |control|
    control.vm.network "private_network", ip:  MASTER_IP
    control.vm.hostname = VM_MASTER_NAME
    control.vm.synced_folder ".",  "/vagrant"
    
    control.vm.provision "shell" do |p|
      p.privileged= true, 
      p.path= "scripts/master.sh", 
      p.args= [MASTER_IP, "Installing Master Node"]
    end
    control.vm.provider "virtualbox" do |vb|
      vb.memory=MEM
      vb.cpus=CPU
      vb.name=VM_MASTER_NAME
      # vb.customize ["modifyvm", :id, "--name", "oouklichS"]
    end
  end

  # this is Worker Node or Agent Node.
  config.vm.define VM_WORKER_NAME do |control|
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.hostname = VM_WORKER_NAME
    control.vm.synced_folder ".",  "/vagrant"
    control.vm.provision "shell", privileged: true, path: "scripts/worker.sh", args: [WORKER_IP, MASTER_IP, "Installing Worker Node"]
    control.vm.provider "virtualbox" do |vb|
      vb.memory=MEM
      vb.cpus=CPU
      vb.name=VM_WORKER_NAME
    end
  end
end